"""
보고서 완료 후 HTML 파일 마무리 및 PDF 생성 유틸리티
"""
import os
import re
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

class ReportFinalizer:
    """보고서 마무리 처리 클래스"""
    
    def __init__(self, artifacts_dir: str = "./artifacts"):
        self.artifacts_dir = Path(artifacts_dir)
        
    def finalize_report(self, report_file: str = "progressive_report.html") -> bool:
        """
        보고서 완료 처리: HTML 파일 수정 및 PDF 생성
        
        Args:
            report_file: 보고서 HTML 파일명
            
        Returns:
            bool: 성공 여부
        """
        try:
            report_path = self.artifacts_dir / report_file
            
            if not report_path.exists():
                logger.warning(f"보고서 파일을 찾을 수 없습니다: {report_path}")
                return False
            
            # 1. HTML 파일 수정
            success = self._update_html_footer(report_path)
            if not success:
                logger.error("HTML 파일 수정 실패")
                return False
            
            # # 2. PDF 생성
            # pdf_success = self._generate_pdf(report_path)
            # if not pdf_success:
            #     logger.warning("PDF 생성에 실패했지만 HTML 수정은 완료되었습니다.")
            
            logger.info("보고서 마무리 처리 완료")
            return True
            
        except Exception as e:
            logger.error(f"보고서 마무리 처리 중 오류 발생: {e}")
            return False
    
    def _update_html_footer(self, html_path: Path) -> bool:
        """
        HTML 파일의 하단 메시지를 보고서 완료 정보로 수정
        
        Args:
            html_path: HTML 파일 경로
            
        Returns:
            bool: 성공 여부
        """
        try:
            # HTML 파일 읽기
            with open(html_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # 현재 시간
            current_time = datetime.now()
            completion_time = current_time.strftime("%Y년 %m월 %d일 %H시 %M분")
            
            # 기존 하단 메시지 패턴 찾기
            old_pattern = r'<div style="text-align: center;[^>]*>\s*<em>본 보고서는 점진적으로 작성되고 있습니다\.</em>\s*</div>'
            
            # 새로운 하단 메시지
            new_footer = f'''<div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; color: #666; font-size: 0.9em;">
        <div style="margin-bottom: 10px;">
            <strong>📋 보고서 작성 완료</strong>
        </div>
        <div style="margin-bottom: 5px;">
            <em>작성 완료 일시: {completion_time}</em>
        </div>
        <div style="font-size: 0.8em; color: #888;">
            Generated by Agentic Research System, AI Solution Team 1
        </div>
    </div>'''
            
            # 패턴 매칭하여 교체
            if re.search(old_pattern, content, re.IGNORECASE | re.DOTALL):
                updated_content = re.sub(old_pattern, new_footer, content, flags=re.IGNORECASE | re.DOTALL)
                logger.info("기존 진행 메시지를 완료 메시지로 교체했습니다.")
            else:
                # 패턴이 없으면 </body> 태그 앞에 추가
                body_end_pattern = r'</body>'
                if re.search(body_end_pattern, content, re.IGNORECASE):
                    updated_content = re.sub(body_end_pattern, f'{new_footer}\n</body>', content, flags=re.IGNORECASE)
                    logger.info("HTML 하단에 완료 메시지를 추가했습니다.")
                else:
                    # </body> 태그도 없으면 파일 끝에 추가
                    updated_content = content + '\n' + new_footer
                    logger.info("파일 끝에 완료 메시지를 추가했습니다.")
            
            # 수정된 내용을 파일에 저장
            with open(html_path, 'w', encoding='utf-8') as f:
                f.write(updated_content)
            
            logger.info(f"HTML 파일 수정 완료: {html_path}")
            return True
            
        except Exception as e:
            logger.error(f"HTML 파일 수정 중 오류 발생: {e}")
            return False
    
    def _generate_pdf(self, html_path: Path) -> bool:
        """
        HTML 파일을 PDF로 변환
        
        Args:
            html_path: HTML 파일 경로
            
        Returns:
            bool: 성공 여부
        """
        try:
            pdf_path = html_path.with_suffix('.pdf')
            
            # 여러 PDF 생성 방법을 시도
            methods = [
                self._generate_pdf_with_weasyprint,
                self._generate_pdf_with_pdfkit,
                self._generate_pdf_with_playwright
            ]
            
            for method in methods:
                try:
                    success = method(html_path, pdf_path)
                    if success:
                        logger.info(f"PDF 생성 완료: {pdf_path}")
                        return True
                except ImportError as e:
                    logger.debug(f"PDF 생성 라이브러리 없음 ({method.__name__}): {e}")
                    continue
                except Exception as e:
                    logger.debug(f"PDF 생성 실패 ({method.__name__}): {e}")
                    continue
            
            logger.warning("모든 PDF 생성 방법이 실패했습니다. 필요한 라이브러리를 설치해주세요.")
            return False
            
        except Exception as e:
            logger.error(f"PDF 생성 중 오류 발생: {e}")
            return False
    
    def _generate_pdf_with_weasyprint(self, html_path: Path, pdf_path: Path) -> bool:
        """WeasyPrint를 사용한 PDF 생성"""
        try:
            import weasyprint
            
            # HTML을 PDF로 변환
            html_doc = weasyprint.HTML(filename=str(html_path))
            html_doc.write_pdf(str(pdf_path))
            
            return True
        except ImportError:
            raise ImportError("weasyprint가 설치되지 않았습니다. 'pip install weasyprint' 실행하세요.")
    
    def _generate_pdf_with_pdfkit(self, html_path: Path, pdf_path: Path) -> bool:
        """pdfkit (wkhtmltopdf)를 사용한 PDF 생성"""
        try:
            import pdfkit
            
            options = {
                'page-size': 'A4',
                'margin-top': '0.75in',
                'margin-right': '0.75in',
                'margin-bottom': '0.75in',
                'margin-left': '0.75in',
                'encoding': "UTF-8",
                'no-outline': None,
                'enable-local-file-access': None
            }
            
            pdfkit.from_file(str(html_path), str(pdf_path), options=options)
            return True
            
        except ImportError:
            raise ImportError("pdfkit이 설치되지 않았습니다. 'pip install pdfkit' 실행하세요.")
        except OSError:
            raise OSError("wkhtmltopdf가 시스템에 설치되지 않았습니다.")
    
    def _generate_pdf_with_playwright(self, html_path: Path, pdf_path: Path) -> bool:
        """Playwright를 사용한 PDF 생성"""
        try:
            from playwright.sync_api import sync_playwright
            
            with sync_playwright() as p:
                browser = p.chromium.launch()
                page = browser.new_page()
                
                # HTML 파일 로드
                page.goto(f"file://{html_path.absolute()}")
                
                # PDF 생성
                page.pdf(
                    path=str(pdf_path),
                    format='A4',
                    margin={
                        'top': '1in',
                        'right': '1in', 
                        'bottom': '1in',
                        'left': '1in'
                    },
                    print_background=True
                )
                
                browser.close()
            
            return True
            
        except ImportError:
            raise ImportError("playwright가 설치되지 않았습니다. 'pip install playwright' 실행하세요.")

def finalize_report(artifacts_dir: str = "./artifacts", report_file: str = "progressive_report.html") -> bool:
    """
    보고서 완료 처리 함수 (편의 함수)
    
    Args:
        artifacts_dir: 아티팩트 디렉토리 경로
        report_file: 보고서 HTML 파일명
        
    Returns:
        bool: 성공 여부
    """
    finalizer = ReportFinalizer(artifacts_dir)
    return finalizer.finalize_report(report_file) 